import os
import json
import uuid
from fastapi import APIRouter, HTTPException
from google import genai

from models import SessionRequest
from database import get_db_connection

router = APIRouter()

def get_gemini_client():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key or api_key == "your_key":
         raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured properly")
    return genai.Client()

def parse_gemini_json(text: str):
    # Strip any ```json fences before parsing
    clean_text = text.strip()
    if clean_text.startswith("```json"):
        clean_text = clean_text[7:]
    elif clean_text.startswith("```"):
        clean_text = clean_text[3:]
    if clean_text.endswith("```"):
        clean_text = clean_text[:-3]
    return json.loads(clean_text)

@router.post("/session")
def create_session(request: SessionRequest):
    client = get_gemini_client()
    chips_str = ",".join(request.chips)
    
    prompt = f"""
Generate exactly 10 feed cards for a CS student focused on: {chips_str}.
Mix these types evenly: insight, repo, challenge, pattern.

Return ONLY a valid JSON array, no markdown, no backticks, no explanation.
Format:
[
  {{
    "id": 1,
    "type": "insight",
    "title": "Short punchy title",
    "body": "Max 2 lines. Dense, useful, no fluff.",
    "tag": "one of the chips",
    "next_action": "One terminal command or concrete step",
    "emoji": "relevant emoji"
  }}
]
"""
    
    # Try calling Gemini and parsing JSON, with one retry
    cards = None
    for attempt in range(2):
        try:
            # Call Gemini to generate 10 feed cards
            response = client.models.generate_content(
                model="gemini-3-flash-preview",
                contents=prompt
            )
            cards = parse_gemini_json(response.text)
            if isinstance(cards, list) and len(cards) > 0:
                break
            else:
                raise ValueError("Response is not a valid list of cards")
        except Exception as e:
            if attempt == 1:
                raise HTTPException(status_code=500, detail="Failed to generate or parse feed cards from Gemini")
            # else loop continues to retry
            
    # Generate new session UUID (simulated as backend generated, but user prompt says "session_id is a uuid generated by frontend",
    # wait: "no auth, no login, session_id is a uuid generated by frontend" - BUT the /session endpoint returns "session_id": "uuid".
    # User said: `POST /session` -> Returns `{ "session_id": "uuid", ... }`. 
    # Let's generate it in the backend for the /session endpoint since it's returning it, 
    # but the frontend uses that returned UUID in `/reflect`. That fulfills both requirements.
    session_id = str(uuid.uuid4())
    
    # Save session to DB
    conn = get_db_connection()
    c = conn.cursor()
    c.execute(
        "INSERT INTO sessions (id, chips) VALUES (?, ?)", 
        (session_id, chips_str)
    )
    conn.commit()
    conn.close()
    
    return {
        "session_id": session_id,
        "cards": cards
    }
